[package]
name = "topoglyph-atlas"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Built-in and custom-font glyph atlas construction for TopoGlyph"

[dependencies]
rusttype = "0.9.3"
topoglyph-core = { workspace = true }
unicode-segmentation = "1.13.3"
unicode-width = "0.2.2"
